//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.MetaData.Discogs.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Artwork.
        /// </summary>
        internal static string DiscogsBehaviour_LookupArtwork {
            get {
                return ResourceManager.GetString("DiscogsBehaviour.LookupArtwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Url.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_BaseUrl {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Key.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_ConsumerKey {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.ConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Secret.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_ConsumerSecret {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.ConsumerSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_Enabled {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discogs.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_Section {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string LookupArtworkReport_Album {
            get {
                return ResourceManager.GetString("LookupArtworkReport.Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string LookupArtworkReport_Artist {
            get {
                return ResourceManager.GetString("LookupArtworkReport.Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string LookupArtworkReport_Release {
            get {
                return ResourceManager.GetString("LookupArtworkReport.Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LookupArtworkReport_Status {
            get {
                return ResourceManager.GetString("LookupArtworkReport.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist and album data is required..
        /// </summary>
        internal static string LookupArtworkTask_InsufficiantData {
            get {
                return ResourceManager.GetString("LookupArtworkTask.InsufficiantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching artwork...
        /// </summary>
        internal static string LookupArtworkTask_Name {
            get {
                return ResourceManager.GetString("LookupArtworkTask.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No release or artwork found..
        /// </summary>
        internal static string LookupArtworkTask_NotFound {
            get {
                return ResourceManager.GetString("LookupArtworkTask.NotFound", resourceCulture);
            }
        }
    }
}
