//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.MetaData.Discogs.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various.
        /// </summary>
        internal static string Discogs_CompilationArtist {
            get {
                return ResourceManager.GetString("Discogs.CompilationArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Artwork.
        /// </summary>
        internal static string DiscogsBehaviour_FetchArtwork {
            get {
                return ResourceManager.GetString("DiscogsBehaviour.FetchArtwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Tags.
        /// </summary>
        internal static string DiscogsBehaviour_FetchTags {
            get {
                return ResourceManager.GetString("DiscogsBehaviour.FetchTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Lookup.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_AutoLookup {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.AutoLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Url.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_BaseUrl {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Lookup.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_ConfirmLookup {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.ConfirmLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Key.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_ConsumerKey {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.ConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer Secret.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_ConsumerSecret {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.ConsumerSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_Enabled {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests Per Second.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_MaxRequests {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.MaxRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Confidence.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_MinConfidence {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.MinConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discogs.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_Section {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Tags.
        /// </summary>
        internal static string DiscogsBehaviourConfiguration_WriteTags {
            get {
                return ResourceManager.GetString("DiscogsBehaviourConfiguration.WriteTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No artwork found..
        /// </summary>
        internal static string DiscogsFetchArtworkTask_NotFound {
            get {
                return ResourceManager.GetString("DiscogsFetchArtworkTask.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist and album data is required..
        /// </summary>
        internal static string DiscogsLookupTask_InsufficiantData {
            get {
                return ResourceManager.GetString("DiscogsLookupTask.InsufficiantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No release found..
        /// </summary>
        internal static string DiscogsLookupTask_NotFound {
            get {
                return ResourceManager.GetString("DiscogsLookupTask.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string General_Advanced {
            get {
                return ResourceManager.GetString("General.Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching artwork...
        /// </summary>
        internal static string LookupArtworkTask_Name {
            get {
                return ResourceManager.GetString("LookupArtworkTask.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching tags...
        /// </summary>
        internal static string LookupTagsTask_Name {
            get {
                return ResourceManager.GetString("LookupTagsTask.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string ReleaseLookupReport_Album {
            get {
                return ResourceManager.GetString("ReleaseLookupReport.Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string ReleaseLookupReport_Artist {
            get {
                return ResourceManager.GetString("ReleaseLookupReport.Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string ReleaseLookupReport_Release {
            get {
                return ResourceManager.GetString("ReleaseLookupReport.Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ReleaseLookupReport_Status {
            get {
                return ResourceManager.GetString("ReleaseLookupReport.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Lookup.
        /// </summary>
        internal static string ReleaseLookupReport_Title {
            get {
                return ResourceManager.GetString("ReleaseLookupReport.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ReleaseSelectionReport_Confirm {
            get {
                return ResourceManager.GetString("ReleaseSelectionReport.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string ReleaseSelectionReport_ReleaseId {
            get {
                return ResourceManager.GetString("ReleaseSelectionReport.ReleaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ReleaseSelectionReport_ReleaseTitle {
            get {
                return ResourceManager.GetString("ReleaseSelectionReport.ReleaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string ReleaseSelectionReport_ReleaseUrl {
            get {
                return ResourceManager.GetString("ReleaseSelectionReport.ReleaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Selection: {0} - {1} ({2} tracks).
        /// </summary>
        internal static string ReleaseSelectionReport_Title {
            get {
                return ResourceManager.GetString("ReleaseSelectionReport.Title", resourceCulture);
            }
        }
    }
}
