//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.Output.Bass.Wasapi.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async.
        /// </summary>
        internal static string BassWasapiStreamOutputConfiguration_Async {
            get {
                return ResourceManager.GetString("BassWasapiStreamOutputConfiguration.Async", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Length.
        /// </summary>
        internal static string BassWasapiStreamOutputConfiguration_BufferLength {
            get {
                return ResourceManager.GetString("BassWasapiStreamOutputConfiguration.BufferLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string BassWasapiStreamOutputConfiguration_Device {
            get {
                return ResourceManager.GetString("BassWasapiStreamOutputConfiguration.Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dither.
        /// </summary>
        internal static string BassWasapiStreamOutputConfiguration_Dither {
            get {
                return ResourceManager.GetString("BassWasapiStreamOutputConfiguration.Dither", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Buffer.
        /// </summary>
        internal static string BassWasapiStreamOutputConfiguration_DoubleBuffer {
            get {
                return ResourceManager.GetString("BassWasapiStreamOutputConfiguration.DoubleBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string BassWasapiStreamOutputConfiguration_Event {
            get {
                return ResourceManager.GetString("BassWasapiStreamOutputConfiguration.Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive.
        /// </summary>
        internal static string BassWasapiStreamOutputConfiguration_Exclusive {
            get {
                return ResourceManager.GetString("BassWasapiStreamOutputConfiguration.Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer.
        /// </summary>
        internal static string BassWasapiStreamOutputConfiguration_Mixer {
            get {
                return ResourceManager.GetString("BassWasapiStreamOutputConfiguration.Mixer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string BassWasapiStreamOutputConfiguration_Mode {
            get {
                return ResourceManager.GetString("BassWasapiStreamOutputConfiguration.Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        internal static string BassWasapiStreamOutputConfiguration_Raw {
            get {
                return ResourceManager.GetString("BassWasapiStreamOutputConfiguration.Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Devices.
        /// </summary>
        internal static string BassWasapiStreamOutputConfiguration_RefreshDevices {
            get {
                return ResourceManager.GetString("BassWasapiStreamOutputConfiguration.RefreshDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string BassWasapiStreamOutputConfiguration_Section {
            get {
                return ResourceManager.GetString("BassWasapiStreamOutputConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WASAPI.
        /// </summary>
        internal static string WASAPI {
            get {
                return ResourceManager.GetString("WASAPI", resourceCulture);
            }
        }
    }
}
