//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.UI.Windows.Layout.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;FoxTunes&gt;
        ///  &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///    &lt;UIComponentConfiguration Component=&quot;3451DAA4-C643-4CB2-8105-B441F0277559&quot;&gt;
        ///      &lt;UIComponentConfiguration Component=&quot;18E98420-F039-4504-A116-3D0F26BEAAD5&quot;&gt;
        ///        &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///          &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///            &lt;UIComponentConfiguration  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Main_1 {
            get {
                return ResourceManager.GetString("Main_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;FoxTunes&gt;
        ///  &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///    &lt;UIComponentConfiguration Component=&quot;3451DAA4-C643-4CB2-8105-B441F0277559&quot;&gt;
        ///      &lt;UIComponentConfiguration Component=&quot;18E98420-F039-4504-A116-3D0F26BEAAD5&quot;&gt;
        ///        &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///          &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///            &lt;UIComponentConfiguration  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Main_2 {
            get {
                return ResourceManager.GetString("Main_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;FoxTunes&gt;
        ///  &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///    &lt;UIComponentConfiguration Component=&quot;A6820FDA-E415-40C6-AEFB-A73B6FBE4C93&quot;&gt;
        ///      &lt;UIComponentConfiguration Component=&quot;3451DAA4-C643-4CB2-8105-B441F0277559&quot;&gt;
        ///        &lt;UIComponentConfiguration Component=&quot;18E98420-F039-4504-A116-3D0F26BEAAD5&quot;&gt;
        ///          &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///            &lt;UIComponentConfiguration  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Main_3 {
            get {
                return ResourceManager.GetString("Main_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;FoxTunes&gt;
        ///  &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///    &lt;UIComponentConfiguration Component=&quot;A6820FDA-E415-40C6-AEFB-A73B6FBE4C93&quot;&gt;
        ///      &lt;UIComponentConfiguration Component=&quot;3451DAA4-C643-4CB2-8105-B441F0277559&quot;&gt;
        ///        &lt;UIComponentConfiguration Component=&quot;18E98420-F039-4504-A116-3D0F26BEAAD5&quot;&gt;
        ///          &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///            &lt;UIComponentConfiguration  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Main_4 {
            get {
                return ResourceManager.GetString("Main_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;FoxTunes&gt;
        ///  &lt;UIComponentConfiguration Component=&quot;3451DAA4-C643-4CB2-8105-B441F0277559&quot;&gt;
        ///    &lt;UIComponentConfiguration Component=&quot;8A4E9DDB-2390-455D-9BA9-57C9A441CD75&quot;&gt;
        ///      &lt;MetaDataEntry Name=&quot;Configuration_AABBBC99-41C7-4563-BB7E-12EDAC59E57F&quot; Value=&quot;30&quot; /&gt;
        ///      &lt;MetaDataEntry Name=&quot;Configuration_AAAA1509-4808-419D-93BB-B8D914C60646&quot; Value=&quot;pack://application:,,,/FoxTunes.UI.Windows.Layout;component/Resources/001.jpg &amp;#xD;&amp;#xA;pack://application:,,,/Fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Main_5 {
            get {
                return ResourceManager.GetString("Main_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;FoxTunes&gt;
        ///  &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///    &lt;UIComponentConfiguration Component=&quot;3451DAA4-C643-4CB2-8105-B441F0277559&quot;&gt;
        ///      &lt;UIComponentConfiguration Component=&quot;A6820FDA-E415-40C6-AEFB-A73B6FBE4C93&quot;&gt;
        ///        &lt;UIComponentConfiguration Component=&quot;67A0F63C-DC86-4B4E-91E1-290B71822853&quot;&gt;
        ///          &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///            &lt;UIComponentConfiguration  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Main_6 {
            get {
                return ResourceManager.GetString("Main_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;FoxTunes&gt;
        ///  &lt;UIComponentConfiguration Component=&quot;3451DAA4-C643-4CB2-8105-B441F0277559&quot;&gt;
        ///    &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///      &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///        &lt;UIComponentConfiguration Component=&quot;18E98420-F039-4504-A116-3D0F26BEAAD5&quot;&gt;
        ///          &lt;UIComponentConfiguration Component=&quot;A6820FDA-E415-40C6-AEFB-A73B6FBE4C93&quot;&gt;
        ///            &lt;UIComponentConfiguration  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Main_7 {
            get {
                return ResourceManager.GetString("Main_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;FoxTunes&gt;
        ///  &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///    &lt;UIComponentConfiguration Component=&quot;3451DAA4-C643-4CB2-8105-B441F0277559&quot;&gt;
        ///      &lt;UIComponentConfiguration Component=&quot;12023E31-CB53-4F9C-8A5B-A0593706F37E&quot;/&gt;
        ///      &lt;UIComponentConfiguration Component=&quot;EDC787A6-7B1E-4161-B2E1-843C58806D81&quot;&gt;
        ///        &lt;MetaDataEntry Name=&quot;VerticalAlignment&quot; Value=&quot;Bottom&quot; /&gt;
        ///        &lt;MetaDataEntry Name=&quot;HorizontalAlignment&quot; Value=&quot;Ri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simple_1 {
            get {
                return ResourceManager.GetString("Simple_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;FoxTunes&gt;
        ///  &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///    &lt;UIComponentConfiguration Component=&quot;3451DAA4-C643-4CB2-8105-B441F0277559&quot;&gt;
        ///      &lt;UIComponentConfiguration Component=&quot;18E98420-F039-4504-A116-3D0F26BEAAD5&quot;&gt;
        ///        &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///          &lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///            &lt;UIComponentConfiguration  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simple_2 {
            get {
                return ResourceManager.GetString("Simple_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;FoxTunes&gt;
        ///	&lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///		&lt;UIComponentConfiguration Component=&quot;3451DAA4-C643-4CB2-8105-B441F0277559&quot;&gt;
        ///			&lt;UIComponentConfiguration Component=&quot;18E98420-F039-4504-A116-3D0F26BEAAD5&quot;&gt;
        ///				&lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///					&lt;UIComponentConfiguration Component=&quot;3E899F79-380C-4EF7-8570-4B4E3B3467CB&quot;&gt;
        ///						&lt;UIComponentConfiguration Component=&quot;86276AD4-3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simple_3 {
            get {
                return ResourceManager.GetString("Simple_3", resourceCulture);
            }
        }
    }
}
