//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.UI.Windows.Layout.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string LayoutDesignerBehaviour_Design {
            get {
                return ResourceManager.GetString("LayoutDesignerBehaviour.Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Preset.
        /// </summary>
        internal static string LayoutDesignerBehaviour_Load {
            get {
                return ResourceManager.GetString("LayoutDesignerBehaviour.Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current layout has been modified, overwrite it?.
        /// </summary>
        internal static string LayoutDesignerBehaviour_Overwrite {
            get {
                return ResourceManager.GetString("LayoutDesignerBehaviour.Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string LayoutDesignerBehaviour_Path {
            get {
                return ResourceManager.GetString("LayoutDesignerBehaviour.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Layout.
        /// </summary>
        internal static string LayoutDesignerBehaviourTask_Name {
            get {
                return ResourceManager.GetString("LayoutDesignerBehaviourTask.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Layout.
        /// </summary>
        internal static string LayoutDesignerKeyBindingsBehaviourConfiguration_Edit {
            get {
                return ResourceManager.GetString("LayoutDesignerKeyBindingsBehaviourConfiguration.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Editing Mode.
        /// </summary>
        internal static string LayoutEditingMode_LayoutEditingMode {
            get {
                return ResourceManager.GetString("LayoutEditingMode.LayoutEditingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Editing Mode.
        /// </summary>
        internal static string LayoutEditingMode_Name {
            get {
                return ResourceManager.GetString("LayoutEditingMode.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string LayoutEditor_Cancel {
            get {
                return ResourceManager.GetString("LayoutEditor.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string LayoutEditor_Save {
            get {
                return ResourceManager.GetString("LayoutEditor.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Selector.
        /// </summary>
        internal static string LayoutSelector_Name {
            get {
                return ResourceManager.GetString("LayoutSelector.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Tree.
        /// </summary>
        internal static string LayoutTreeWindow_Title {
            get {
                return ResourceManager.GetString("LayoutTreeWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string ToolWindowBehaviour_Manage {
            get {
                return ResourceManager.GetString("ToolWindowBehaviour.Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ToolWindowBehaviour_New {
            get {
                return ResourceManager.GetString("ToolWindowBehaviour.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Window.
        /// </summary>
        internal static string ToolWindowBehaviour_NewWindow {
            get {
                return ResourceManager.GetString("ToolWindowBehaviour.NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs.
        /// </summary>
        internal static string ToolWindowBehaviour_Path {
            get {
                return ResourceManager.GetString("ToolWindowBehaviour.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs.
        /// </summary>
        internal static string ToolWindowKeyBindingsBehaviourConfiguration_Manage {
            get {
                return ResourceManager.GetString("ToolWindowKeyBindingsBehaviourConfiguration.Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On Top.
        /// </summary>
        internal static string ToolWindowManager_AlwaysOnTop {
            get {
                return ResourceManager.GetString("ToolWindowManager.AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        internal static string ToolWindowManager_Component {
            get {
                return ResourceManager.GetString("ToolWindowManager.Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Main.
        /// </summary>
        internal static string ToolWindowManager_CopyToMain {
            get {
                return ResourceManager.GetString("ToolWindowManager.CopyToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Layout XML.
        /// </summary>
        internal static string ToolWindowManager_EditLayoutXML {
            get {
                return ResourceManager.GetString("ToolWindowManager.EditLayoutXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show With Main Window.
        /// </summary>
        internal static string ToolWindowManager_MainWindow {
            get {
                return ResourceManager.GetString("ToolWindowManager.MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show With Mini Window.
        /// </summary>
        internal static string ToolWindowManager_MiniWindow {
            get {
                return ResourceManager.GetString("ToolWindowManager.MiniWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ToolWindowManager_Title {
            get {
                return ResourceManager.GetString("ToolWindowManager.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Manager.
        /// </summary>
        internal static string ToolWindowManagerWindow_Title {
            get {
                return ResourceManager.GetString("ToolWindowManagerWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string UIComponentContainer_Clear {
            get {
                return ResourceManager.GetString("UIComponentContainer.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string UIComponentContainer_Exit {
            get {
                return ResourceManager.GetString("UIComponentContainer.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string UIComponentContainer_Replace {
            get {
                return ResourceManager.GetString("UIComponentContainer.Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap.
        /// </summary>
        internal static string UIComponentContainer_Wrap {
            get {
                return ResourceManager.GetString("UIComponentContainer.Wrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout\{0}.
        /// </summary>
        internal static string UIComponentDesignerOverlay_Path_Child {
            get {
                return ResourceManager.GetString("UIComponentDesignerOverlay.Path.Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout\{0} (Container).
        /// </summary>
        internal static string UIComponentDesignerOverlay_Path_Parent {
            get {
                return ResourceManager.GetString("UIComponentDesignerOverlay.Path.Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsable.
        /// </summary>
        internal static string UIComponentDockContainer_Collapse {
            get {
                return ResourceManager.GetString("UIComponentDockContainer.Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock Bottom.
        /// </summary>
        internal static string UIComponentDockContainer_DockBottom {
            get {
                return ResourceManager.GetString("UIComponentDockContainer.DockBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock Left.
        /// </summary>
        internal static string UIComponentDockContainer_DockLeft {
            get {
                return ResourceManager.GetString("UIComponentDockContainer.DockLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock Right.
        /// </summary>
        internal static string UIComponentDockContainer_DockRight {
            get {
                return ResourceManager.GetString("UIComponentDockContainer.DockRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock Top.
        /// </summary>
        internal static string UIComponentDockContainer_DockTop {
            get {
                return ResourceManager.GetString("UIComponentDockContainer.DockTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        internal static string UIComponentDockContainer_Name {
            get {
                return ResourceManager.GetString("UIComponentDockContainer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string UIComponentGridContainer_Add {
            get {
                return ResourceManager.GetString("UIComponentGridContainer.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Bottom.
        /// </summary>
        internal static string UIComponentGridContainer_AlignBottom {
            get {
                return ResourceManager.GetString("UIComponentGridContainer.AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Left.
        /// </summary>
        internal static string UIComponentGridContainer_AlignLeft {
            get {
                return ResourceManager.GetString("UIComponentGridContainer.AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Right.
        /// </summary>
        internal static string UIComponentGridContainer_AlignRight {
            get {
                return ResourceManager.GetString("UIComponentGridContainer.AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Center.
        /// </summary>
        internal static string UIComponentGridContainer_AlignStretch {
            get {
                return ResourceManager.GetString("UIComponentGridContainer.AlignStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Top.
        /// </summary>
        internal static string UIComponentGridContainer_AlignTop {
            get {
                return ResourceManager.GetString("UIComponentGridContainer.AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string UIComponentGridContainer_MoveDown {
            get {
                return ResourceManager.GetString("UIComponentGridContainer.MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Left.
        /// </summary>
        internal static string UIComponentGridContainer_MoveLeft {
            get {
                return ResourceManager.GetString("UIComponentGridContainer.MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Right.
        /// </summary>
        internal static string UIComponentGridContainer_MoveRight {
            get {
                return ResourceManager.GetString("UIComponentGridContainer.MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string UIComponentGridContainer_MoveUp {
            get {
                return ResourceManager.GetString("UIComponentGridContainer.MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UIComponentGridContainer_Name {
            get {
                return ResourceManager.GetString("UIComponentGridContainer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string UIComponentGridContainer_Remove {
            get {
                return ResourceManager.GetString("UIComponentGridContainer.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Box.
        /// </summary>
        internal static string UIComponentGroupContainer_Name {
            get {
                return ResourceManager.GetString("UIComponentGroupContainer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string UIComponentGroupContainer_Rename {
            get {
                return ResourceManager.GetString("UIComponentGroupContainer.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Grid.
        /// </summary>
        internal static string UIComponentHorizontalGridContainer_Name {
            get {
                return ResourceManager.GetString("UIComponentHorizontalGridContainer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Bottom.
        /// </summary>
        internal static string UIComponentHorizontalSplitContainer_CollapseBottom {
            get {
                return ResourceManager.GetString("UIComponentHorizontalSplitContainer.CollapseBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Top.
        /// </summary>
        internal static string UIComponentHorizontalSplitContainer_CollapseTop {
            get {
                return ResourceManager.GetString("UIComponentHorizontalSplitContainer.CollapseTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Bottom.
        /// </summary>
        internal static string UIComponentHorizontalSplitContainer_FreezeBottom {
            get {
                return ResourceManager.GetString("UIComponentHorizontalSplitContainer.FreezeBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Top.
        /// </summary>
        internal static string UIComponentHorizontalSplitContainer_FreezeTop {
            get {
                return ResourceManager.GetString("UIComponentHorizontalSplitContainer.FreezeTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitter (top | bottom).
        /// </summary>
        internal static string UIComponentHorizontalSplitContainer_Name {
            get {
                return ResourceManager.GetString("UIComponentHorizontalSplitContainer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UIComponentLayoutProvider_Description {
            get {
                return ResourceManager.GetString("UIComponentLayoutProvider.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizable.
        /// </summary>
        internal static string UIComponentLayoutProvider_Name {
            get {
                return ResourceManager.GetString("UIComponentLayoutProvider.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Layout.
        /// </summary>
        internal static string UIComponentLayoutProviderConfiguration_MainLayout {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderConfiguration.MainLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced\Layouts.
        /// </summary>
        internal static string UIComponentLayoutProviderConfiguration_Path {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderConfiguration.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        internal static string UIComponentLayoutProviderConfiguration_Preset {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderConfiguration.Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string UIComponentLayoutProviderConfiguration_Refresh {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderConfiguration.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string UIComponentLayoutProviderPresets_Main_1 {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderPresets.Main.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (With WaveBar).
        /// </summary>
        internal static string UIComponentLayoutProviderPresets_Main_2 {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderPresets.Main.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (With Visualizations).
        /// </summary>
        internal static string UIComponentLayoutProviderPresets_Main_3 {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderPresets.Main.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (With Visualizations + Properties).
        /// </summary>
        internal static string UIComponentLayoutProviderPresets_Main_4 {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderPresets.Main.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development 1.
        /// </summary>
        internal static string UIComponentLayoutProviderPresets_Main_5 {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderPresets.Main.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development 2.
        /// </summary>
        internal static string UIComponentLayoutProviderPresets_Main_6 {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderPresets.Main.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development 3.
        /// </summary>
        internal static string UIComponentLayoutProviderPresets_Main_7 {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderPresets.Main.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string UIComponentLayoutProviderPresets_Simple_1 {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderPresets.Simple.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple (With Library).
        /// </summary>
        internal static string UIComponentLayoutProviderPresets_Simple_2 {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderPresets.Simple.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple (With Library + Properties).
        /// </summary>
        internal static string UIComponentLayoutProviderPresets_Simple_3 {
            get {
                return ResourceManager.GetString("UIComponentLayoutProviderPresets.Simple.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string UIComponentStackContainer_Add {
            get {
                return ResourceManager.GetString("UIComponentStackContainer.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Bottom.
        /// </summary>
        internal static string UIComponentStackContainer_AlignBottom {
            get {
                return ResourceManager.GetString("UIComponentStackContainer.AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Left.
        /// </summary>
        internal static string UIComponentStackContainer_AlignLeft {
            get {
                return ResourceManager.GetString("UIComponentStackContainer.AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Right.
        /// </summary>
        internal static string UIComponentStackContainer_AlignRight {
            get {
                return ResourceManager.GetString("UIComponentStackContainer.AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Top.
        /// </summary>
        internal static string UIComponentStackContainer_AlignTop {
            get {
                return ResourceManager.GetString("UIComponentStackContainer.AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        internal static string UIComponentStackContainer_Fill {
            get {
                return ResourceManager.GetString("UIComponentStackContainer.Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string UIComponentStackContainer_MoveDown {
            get {
                return ResourceManager.GetString("UIComponentStackContainer.MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string UIComponentStackContainer_MoveUp {
            get {
                return ResourceManager.GetString("UIComponentStackContainer.MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Grid.
        /// </summary>
        internal static string UIComponentStackContainer_Name {
            get {
                return ResourceManager.GetString("UIComponentStackContainer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string UIComponentStackContainer_Remove {
            get {
                return ResourceManager.GetString("UIComponentStackContainer.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tab.
        /// </summary>
        internal static string UIComponentTabContainer_Add {
            get {
                return ResourceManager.GetString("UIComponentTabContainer.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Left.
        /// </summary>
        internal static string UIComponentTabContainer_MoveLeft {
            get {
                return ResourceManager.GetString("UIComponentTabContainer.MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Right.
        /// </summary>
        internal static string UIComponentTabContainer_MoveRight {
            get {
                return ResourceManager.GetString("UIComponentTabContainer.MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs.
        /// </summary>
        internal static string UIComponentTabContainer_Name {
            get {
                return ResourceManager.GetString("UIComponentTabContainer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tab.
        /// </summary>
        internal static string UIComponentTabContainer_NewTab {
            get {
                return ResourceManager.GetString("UIComponentTabContainer.NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Tab.
        /// </summary>
        internal static string UIComponentTabContainer_Remove {
            get {
                return ResourceManager.GetString("UIComponentTabContainer.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string UIComponentTabContainer_Rename {
            get {
                return ResourceManager.GetString("UIComponentTabContainer.Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Name.
        /// </summary>
        internal static string UIComponentTabContainer_TabName {
            get {
                return ResourceManager.GetString("UIComponentTabContainer.TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Toolbar.
        /// </summary>
        internal static string UIComponentToolbar_Name {
            get {
                return ResourceManager.GetString("UIComponentToolbar.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string UIComponentToolbar_Reset {
            get {
                return ResourceManager.GetString("UIComponentToolbar.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Grid.
        /// </summary>
        internal static string UIComponentVerticalGridContainer_Name {
            get {
                return ResourceManager.GetString("UIComponentVerticalGridContainer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Left.
        /// </summary>
        internal static string UIComponentVerticalSplitContainer_CollapseLeft {
            get {
                return ResourceManager.GetString("UIComponentVerticalSplitContainer.CollapseLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Right.
        /// </summary>
        internal static string UIComponentVerticalSplitContainer_CollapseRight {
            get {
                return ResourceManager.GetString("UIComponentVerticalSplitContainer.CollapseRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Left.
        /// </summary>
        internal static string UIComponentVerticalSplitContainer_FreezeLeft {
            get {
                return ResourceManager.GetString("UIComponentVerticalSplitContainer.FreezeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Right.
        /// </summary>
        internal static string UIComponentVerticalSplitContainer_FreezeRight {
            get {
                return ResourceManager.GetString("UIComponentVerticalSplitContainer.FreezeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitter (left | right).
        /// </summary>
        internal static string UIComponentVerticalSplitContainer_Name {
            get {
                return ResourceManager.GetString("UIComponentVerticalSplitContainer.Name", resourceCulture);
            }
        }
    }
}
