//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.Scripting.JS.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function () {
        ///  var parts = [];
        ///
        ///  if (tag.__ft_variousartists) {
        ///    parts.push(&quot;Various Artists&quot;);
        ///  }
        ///  else {
        ///    if (tag.firstalbumartist || tag.firstalbumartistsort || tag.firstartist) {
        ///      parts.push(tag.firstalbumartist || tag.firstalbumartistsort || tag.firstartist);
        ///    }
        ///  }
        ///
        ///  if (tag.year) {
        ///    parts.push(tag.year);
        ///  }
        ///
        ///  if (tag.album) {
        ///    parts.push(tag.album);
        ///  }
        ///
        ///  if (tag.disccount != 1 &amp;&amp; tag.disc) {
        ///    parts.push(tag.disc);
        ///  }
        ///
        ///  if (tag.track) {
        ///    p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlaylistSortValues {
            get {
                return ResourceManager.GetString("PlaylistSortValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function version() {
        ///    return &quot;Fox Tunes 0.9&quot;;
        ///}
        ///
        ///function timestamp(value) {
        ///
        ///    if (!value) {
        ///        return value;
        ///    }
        ///
        ///    var s = parseInt((value / 1000) % 60);
        ///    var m = parseInt((value / (1000 * 60)) % 60);
        ///    var h = parseInt((value / (1000 * 60 * 60)) % 24);
        ///
        ///    var parts = [];
        ///
        ///    if (h &gt; 0) {
        ///        if (h &lt; 10) {
        ///            h = &quot;0&quot; + h;
        ///        }
        ///        parts.push(h);
        ///    }
        ///
        ///    if (m &lt; 10) {
        ///        m = &quot;0&quot; + m;
        ///    }
        ///    parts.push(m);
        ///    if (s &lt; 10) {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string utils {
            get {
                return ResourceManager.GetString("utils", resourceCulture);
            }
        }
    }
}
