//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.UI.Windows.Visualizations.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum.
        /// </summary>
        internal static string EnhancedSpectrum_Name {
            get {
                return ResourceManager.GetString("EnhancedSpectrum.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bands.
        /// </summary>
        internal static string EnhancedSpectrumConfiguration_Bands {
            get {
                return ResourceManager.GetString("EnhancedSpectrumConfiguration.Bands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config (Min Max Count).
        /// </summary>
        internal static string EnhancedSpectrumConfiguration_Bands_Custom {
            get {
                return ResourceManager.GetString("EnhancedSpectrumConfiguration.Bands.Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Max Count Function(L = Linear, S = Square).
        /// </summary>
        internal static string EnhancedSpectrumConfiguration_Bands_Custom_Description {
            get {
                return ResourceManager.GetString("EnhancedSpectrumConfiguration.Bands.Custom.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Palette.
        /// </summary>
        internal static string EnhancedSpectrumConfiguration_ColorPalette {
            get {
                return ResourceManager.GetString("EnhancedSpectrumConfiguration.ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string EnhancedSpectrumConfiguration_Duration {
            get {
                return ResourceManager.GetString("EnhancedSpectrumConfiguration.Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string EnhancedSpectrumConfiguration_Duration_High {
            get {
                return ResourceManager.GetString("EnhancedSpectrumConfiguration.Duration.High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string EnhancedSpectrumConfiguration_Duration_Low {
            get {
                return ResourceManager.GetString("EnhancedSpectrumConfiguration.Duration.Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string EnhancedSpectrumConfiguration_Duration_Medium {
            get {
                return ResourceManager.GetString("EnhancedSpectrumConfiguration.Duration.Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Peak.
        /// </summary>
        internal static string EnhancedSpectrumConfiguration_Peak {
            get {
                return ResourceManager.GetString("EnhancedSpectrumConfiguration.Peak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show RMS.
        /// </summary>
        internal static string EnhancedSpectrumConfiguration_Rms {
            get {
                return ResourceManager.GetString("EnhancedSpectrumConfiguration.Rms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum.
        /// </summary>
        internal static string EnhancedSpectrumConfiguration_Section {
            get {
                return ResourceManager.GetString("EnhancedSpectrumConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string General_Advanced {
            get {
                return ResourceManager.GetString("General.Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscilloscope.
        /// </summary>
        internal static string Oscilloscope_Name {
            get {
                return ResourceManager.GetString("Oscilloscope.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Palette.
        /// </summary>
        internal static string OscilloscopeConfiguration_ColorPalette {
            get {
                return ResourceManager.GetString("OscilloscopeConfiguration.ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (ms).
        /// </summary>
        internal static string OscilloscopeConfiguration_Duration {
            get {
                return ResourceManager.GetString("OscilloscopeConfiguration.Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string OscilloscopeConfiguration_Mode {
            get {
                return ResourceManager.GetString("OscilloscopeConfiguration.Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        internal static string OscilloscopeConfiguration_Mode_Mono {
            get {
                return ResourceManager.GetString("OscilloscopeConfiguration.Mode.Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seperate.
        /// </summary>
        internal static string OscilloscopeConfiguration_Mode_Seperate {
            get {
                return ResourceManager.GetString("OscilloscopeConfiguration.Mode.Seperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscilloscope.
        /// </summary>
        internal static string OscilloscopeConfiguration_Section {
            get {
                return ResourceManager.GetString("OscilloscopeConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window (ms).
        /// </summary>
        internal static string OscilloscopeConfiguration_Window {
            get {
                return ResourceManager.GetString("OscilloscopeConfiguration.Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Meter.
        /// </summary>
        internal static string PeakMeter_Name {
            get {
                return ResourceManager.GetString("PeakMeter.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Palette.
        /// </summary>
        internal static string PeakMeterConfiguration_ColorPalette {
            get {
                return ResourceManager.GetString("PeakMeterConfiguration.ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string PeakMeterConfiguration_Duration {
            get {
                return ResourceManager.GetString("PeakMeterConfiguration.Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string PeakMeterConfiguration_Duration_High {
            get {
                return ResourceManager.GetString("PeakMeterConfiguration.Duration.High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string PeakMeterConfiguration_Duration_Low {
            get {
                return ResourceManager.GetString("PeakMeterConfiguration.Duration.Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string PeakMeterConfiguration_Duration_Medium {
            get {
                return ResourceManager.GetString("PeakMeterConfiguration.Duration.Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Duration.
        /// </summary>
        internal static string PeakMeterConfiguration_Hold {
            get {
                return ResourceManager.GetString("PeakMeterConfiguration.Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Frequency (Hz).
        /// </summary>
        internal static string PeakMeterConfiguration_MaxFrequency {
            get {
                return ResourceManager.GetString("PeakMeterConfiguration.MaxFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Frequency (Hz).
        /// </summary>
        internal static string PeakMeterConfiguration_MinFrequency {
            get {
                return ResourceManager.GetString("PeakMeterConfiguration.MinFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Peaks.
        /// </summary>
        internal static string PeakMeterConfiguration_Peaks {
            get {
                return ResourceManager.GetString("PeakMeterConfiguration.Peaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show RMS.
        /// </summary>
        internal static string PeakMeterConfiguration_Rms {
            get {
                return ResourceManager.GetString("PeakMeterConfiguration.Rms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Meter.
        /// </summary>
        internal static string PeakMeterConfiguration_Section {
            get {
                return ResourceManager.GetString("PeakMeterConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string Speakers_Center {
            get {
                return ResourceManager.GetString("Speakers.Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FL.
        /// </summary>
        internal static string Speakers_FrontLeft {
            get {
                return ResourceManager.GetString("Speakers.FrontLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR.
        /// </summary>
        internal static string Speakers_FrontRight {
            get {
                return ResourceManager.GetString("Speakers.FrontRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string Speakers_Left {
            get {
                return ResourceManager.GetString("Speakers.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LFE.
        /// </summary>
        internal static string Speakers_LFE {
            get {
                return ResourceManager.GetString("Speakers.LFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RL.
        /// </summary>
        internal static string Speakers_RearLeft {
            get {
                return ResourceManager.GetString("Speakers.RearLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RR.
        /// </summary>
        internal static string Speakers_RearRight {
            get {
                return ResourceManager.GetString("Speakers.RearRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string Speakers_Right {
            get {
                return ResourceManager.GetString("Speakers.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string Speakers_Unknown {
            get {
                return ResourceManager.GetString("Speakers.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrogram.
        /// </summary>
        internal static string Spectrogram_Name {
            get {
                return ResourceManager.GetString("Spectrogram.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Palette.
        /// </summary>
        internal static string SpectrogramConfiguration_ColorPalette {
            get {
                return ResourceManager.GetString("SpectrogramConfiguration.ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Buffer Length.
        /// </summary>
        internal static string SpectrogramConfiguration_History {
            get {
                return ResourceManager.GetString("SpectrogramConfiguration.History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string SpectrogramConfiguration_Mode {
            get {
                return ResourceManager.GetString("SpectrogramConfiguration.Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        internal static string SpectrogramConfiguration_Mode_Mono {
            get {
                return ResourceManager.GetString("SpectrogramConfiguration.Mode.Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seperate.
        /// </summary>
        internal static string SpectrogramConfiguration_Mode_Seperate {
            get {
                return ResourceManager.GetString("SpectrogramConfiguration.Mode.Seperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string SpectrogramConfiguration_Scale {
            get {
                return ResourceManager.GetString("SpectrogramConfiguration.Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        internal static string SpectrogramConfiguration_Scale_Linear {
            get {
                return ResourceManager.GetString("SpectrogramConfiguration.Scale.Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithmic.
        /// </summary>
        internal static string SpectrogramConfiguration_Scale_Logarithmic {
            get {
                return ResourceManager.GetString("SpectrogramConfiguration.Scale.Logarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrogram.
        /// </summary>
        internal static string SpectrogramConfiguration_Section {
            get {
                return ResourceManager.GetString("SpectrogramConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing.
        /// </summary>
        internal static string SpectrogramConfiguration_Smoothing {
            get {
                return ResourceManager.GetString("SpectrogramConfiguration.Smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string SpectrogramConfiguration_Smoothing_Off {
            get {
                return ResourceManager.GetString("SpectrogramConfiguration.Smoothing.Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum (Basic).
        /// </summary>
        internal static string Spectrum_Name {
            get {
                return ResourceManager.GetString("Spectrum.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars.
        /// </summary>
        internal static string SpectrumConfiguration_Bars {
            get {
                return ResourceManager.GetString("SpectrumConfiguration.Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Palette.
        /// </summary>
        internal static string SpectrumConfiguration_ColorPalette {
            get {
                return ResourceManager.GetString("SpectrumConfiguration.ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Duration.
        /// </summary>
        internal static string SpectrumConfiguration_Hold {
            get {
                return ResourceManager.GetString("SpectrumConfiguration.Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Frequency (KHz).
        /// </summary>
        internal static string SpectrumConfiguration_MaxFrequency {
            get {
                return ResourceManager.GetString("SpectrumConfiguration.MaxFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Peaks.
        /// </summary>
        internal static string SpectrumConfiguration_Peaks {
            get {
                return ResourceManager.GetString("SpectrumConfiguration.Peaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Amp (dB).
        /// </summary>
        internal static string SpectrumConfiguration_PreAmp {
            get {
                return ResourceManager.GetString("SpectrumConfiguration.PreAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum (Basic).
        /// </summary>
        internal static string SpectrumConfiguration_Section {
            get {
                return ResourceManager.GetString("SpectrumConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Visualization_Speed_Default {
            get {
                return ResourceManager.GetString("Visualization.Speed.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string Visualization_Speed_Fast {
            get {
                return ResourceManager.GetString("Visualization.Speed.Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        internal static string Visualization_Speed_Slow {
            get {
                return ResourceManager.GetString("Visualization.Speed.Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT Size.
        /// </summary>
        internal static string VisualizationBehaviourConfiguration_FFTSize {
            get {
                return ResourceManager.GetString("VisualizationBehaviourConfiguration.FFTSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Interval.
        /// </summary>
        internal static string VisualizationBehaviourConfiguration_Interval {
            get {
                return ResourceManager.GetString("VisualizationBehaviourConfiguration.Interval", resourceCulture);
            }
        }
    }
}
