//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.UI.Windows.Visualizations.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Spectrum.
        /// </summary>
        internal static string EnhancedSpectrum_Name {
            get {
                return ResourceManager.GetString("EnhancedSpectrum.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string General_Advanced {
            get {
                return ResourceManager.GetString("General.Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bands.
        /// </summary>
        internal static string General_Bands {
            get {
                return ResourceManager.GetString("General.Bands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars.
        /// </summary>
        internal static string General_Bars {
            get {
                return ResourceManager.GetString("General.Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscilloscope.
        /// </summary>
        internal static string Oscilloscope_Name {
            get {
                return ResourceManager.GetString("Oscilloscope.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string OscilloscopeBehaviourConfiguration_Duration {
            get {
                return ResourceManager.GetString("OscilloscopeBehaviourConfiguration.Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string OscilloscopeBehaviourConfiguration_Mode {
            get {
                return ResourceManager.GetString("OscilloscopeBehaviourConfiguration.Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        internal static string OscilloscopeBehaviourConfiguration_Mode_Mono {
            get {
                return ResourceManager.GetString("OscilloscopeBehaviourConfiguration.Mode.Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seperate.
        /// </summary>
        internal static string OscilloscopeBehaviourConfiguration_Mode_Seperate {
            get {
                return ResourceManager.GetString("OscilloscopeBehaviourConfiguration.Mode.Seperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscilloscope.
        /// </summary>
        internal static string OscilloscopeBehaviourConfiguration_Path {
            get {
                return ResourceManager.GetString("OscilloscopeBehaviourConfiguration.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Meter.
        /// </summary>
        internal static string PeakMeter_Name {
            get {
                return ResourceManager.GetString("PeakMeter.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string PeakMeterBehaviourConfiguration_Orientation {
            get {
                return ResourceManager.GetString("PeakMeterBehaviourConfiguration.Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string PeakMeterBehaviourConfiguration_Orientation_Horizontal {
            get {
                return ResourceManager.GetString("PeakMeterBehaviourConfiguration.Orientation.Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string PeakMeterBehaviourConfiguration_Orientation_Vertical {
            get {
                return ResourceManager.GetString("PeakMeterBehaviourConfiguration.Orientation.Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Meter.
        /// </summary>
        internal static string PeakMeterBehaviourConfiguration_Path {
            get {
                return ResourceManager.GetString("PeakMeterBehaviourConfiguration.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string Speakers_Center {
            get {
                return ResourceManager.GetString("Speakers.Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FL.
        /// </summary>
        internal static string Speakers_FrontLeft {
            get {
                return ResourceManager.GetString("Speakers.FrontLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR.
        /// </summary>
        internal static string Speakers_FrontRight {
            get {
                return ResourceManager.GetString("Speakers.FrontRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string Speakers_Left {
            get {
                return ResourceManager.GetString("Speakers.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LFE.
        /// </summary>
        internal static string Speakers_LFE {
            get {
                return ResourceManager.GetString("Speakers.LFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RL.
        /// </summary>
        internal static string Speakers_RearLeft {
            get {
                return ResourceManager.GetString("Speakers.RearLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RR.
        /// </summary>
        internal static string Speakers_RearRight {
            get {
                return ResourceManager.GetString("Speakers.RearRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string Speakers_Right {
            get {
                return ResourceManager.GetString("Speakers.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string Speakers_Unknown {
            get {
                return ResourceManager.GetString("Speakers.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrogram.
        /// </summary>
        internal static string Spectrogram_Name {
            get {
                return ResourceManager.GetString("Spectrogram.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Palette.
        /// </summary>
        internal static string SpectrogramBehaviourConfiguration_ColorPalette {
            get {
                return ResourceManager.GetString("SpectrogramBehaviourConfiguration.ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string SpectrogramBehaviourConfiguration_Mode {
            get {
                return ResourceManager.GetString("SpectrogramBehaviourConfiguration.Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        internal static string SpectrogramBehaviourConfiguration_Mode_Mono {
            get {
                return ResourceManager.GetString("SpectrogramBehaviourConfiguration.Mode.Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seperate.
        /// </summary>
        internal static string SpectrogramBehaviourConfiguration_Mode_Seperate {
            get {
                return ResourceManager.GetString("SpectrogramBehaviourConfiguration.Mode.Seperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrogram.
        /// </summary>
        internal static string SpectrogramBehaviourConfiguration_Path {
            get {
                return ResourceManager.GetString("SpectrogramBehaviourConfiguration.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string SpectrogramBehaviourConfiguration_Scale {
            get {
                return ResourceManager.GetString("SpectrogramBehaviourConfiguration.Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        internal static string SpectrogramBehaviourConfiguration_Scale_Linear {
            get {
                return ResourceManager.GetString("SpectrogramBehaviourConfiguration.Scale.Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithmic.
        /// </summary>
        internal static string SpectrogramBehaviourConfiguration_Scale_Logarithmic {
            get {
                return ResourceManager.GetString("SpectrogramBehaviourConfiguration.Scale.Logarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing.
        /// </summary>
        internal static string SpectrogramBehaviourConfiguration_Smoothing {
            get {
                return ResourceManager.GetString("SpectrogramBehaviourConfiguration.Smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string SpectrogramBehaviourConfiguration_Smoothing_Off {
            get {
                return ResourceManager.GetString("SpectrogramBehaviourConfiguration.Smoothing.Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum.
        /// </summary>
        internal static string Spectrum_Name {
            get {
                return ResourceManager.GetString("Spectrum.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bands (Enhanced).
        /// </summary>
        internal static string SpectrumBehaviourConfiguration_Bands {
            get {
                return ResourceManager.GetString("SpectrumBehaviourConfiguration.Bands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bars (Basic).
        /// </summary>
        internal static string SpectrumBehaviourConfiguration_Bars {
            get {
                return ResourceManager.GetString("SpectrumBehaviourConfiguration.Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Crest Factor.
        /// </summary>
        internal static string SpectrumBehaviourConfiguration_Crest {
            get {
                return ResourceManager.GetString("SpectrumBehaviourConfiguration.Crest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Cut.
        /// </summary>
        internal static string SpectrumBehaviourConfiguration_HighCut {
            get {
                return ResourceManager.GetString("SpectrumBehaviourConfiguration.HighCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Duration.
        /// </summary>
        internal static string SpectrumBehaviourConfiguration_Hold {
            get {
                return ResourceManager.GetString("SpectrumBehaviourConfiguration.Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum.
        /// </summary>
        internal static string SpectrumBehaviourConfiguration_Path {
            get {
                return ResourceManager.GetString("SpectrumBehaviourConfiguration.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Peaks.
        /// </summary>
        internal static string SpectrumBehaviourConfiguration_Peaks {
            get {
                return ResourceManager.GetString("SpectrumBehaviourConfiguration.Peaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show RMS.
        /// </summary>
        internal static string SpectrumBehaviourConfiguration_Rms {
            get {
                return ResourceManager.GetString("SpectrumBehaviourConfiguration.Rms", resourceCulture);
            }
        }
    }
}
