//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.Output.Bass.Cd.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CD.
        /// </summary>
        internal static string BassCdStreamProviderBehaviour_Path {
            get {
                return ResourceManager.GetString("BassCdStreamProviderBehaviour.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string BassCdStreamProviderBehaviourConfiguration_Enabled {
            get {
                return ResourceManager.GetString("BassCdStreamProviderBehaviourConfiguration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Hosts.
        /// </summary>
        internal static string BassCdStreamProviderBehaviourConfiguration_Host {
            get {
                return ResourceManager.GetString("BassCdStreamProviderBehaviourConfiguration.Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gnudb.gnudb.org.
        /// </summary>
        internal static string BassCdStreamProviderBehaviourConfiguration_Host1 {
            get {
                return ResourceManager.GetString("BassCdStreamProviderBehaviourConfiguration.Host1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to freedb.dbpoweramp.com.
        /// </summary>
        internal static string BassCdStreamProviderBehaviourConfiguration_Host2 {
            get {
                return ResourceManager.GetString("BassCdStreamProviderBehaviourConfiguration.Host2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Tags.
        /// </summary>
        internal static string BassCdStreamProviderBehaviourConfiguration_Lookup {
            get {
                return ResourceManager.GetString("BassCdStreamProviderBehaviourConfiguration.Lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD.
        /// </summary>
        internal static string BassCdStreamProviderBehaviourConfiguration_Section {
            get {
                return ResourceManager.GetString("BassCdStreamProviderBehaviourConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading CD.
        /// </summary>
        internal static string CdPlaylistItemFactory_Name {
            get {
                return ResourceManager.GetString("CdPlaylistItemFactory.Name", resourceCulture);
            }
        }
    }
}
