//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.Output.Bass.Archive.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading archive.
        /// </summary>
        internal static string ArchiveItemFactory_Name {
            get {
                return ResourceManager.GetString("ArchiveItemFactory.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Archive.
        /// </summary>
        internal static string BassArchiveStreamProviderBehaviour_Open {
            get {
                return ResourceManager.GetString("BassArchiveStreamProviderBehaviour.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Size (%).
        /// </summary>
        internal static string BassArchiveStreamProviderBehaviourConfiguration_BufferMin {
            get {
                return ResourceManager.GetString("BassArchiveStreamProviderBehaviourConfiguration.BufferMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Timeout (ms).
        /// </summary>
        internal static string BassArchiveStreamProviderBehaviourConfiguration_BufferTimeout {
            get {
                return ResourceManager.GetString("BassArchiveStreamProviderBehaviourConfiguration.BufferTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup Temp Files.
        /// </summary>
        internal static string BassArchiveStreamProviderBehaviourConfiguration_Cleanup {
            get {
                return ResourceManager.GetString("BassArchiveStreamProviderBehaviourConfiguration.Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Buffer.
        /// </summary>
        internal static string BassArchiveStreamProviderBehaviourConfiguration_DoubleBuffer {
            get {
                return ResourceManager.GetString("BassArchiveStreamProviderBehaviourConfiguration.DoubleBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string BassArchiveStreamProviderBehaviourConfiguration_Enabled {
            get {
                return ResourceManager.GetString("BassArchiveStreamProviderBehaviourConfiguration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Meta Data.
        /// </summary>
        internal static string BassArchiveStreamProviderBehaviourConfiguration_MetaData {
            get {
                return ResourceManager.GetString("BassArchiveStreamProviderBehaviourConfiguration.MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string BassArchiveStreamProviderBehaviourConfiguration_Section {
            get {
                return ResourceManager.GetString("BassArchiveStreamProviderBehaviourConfiguration.Section", resourceCulture);
            }
        }
    }
}
