//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.UI.Windows.Themes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLACK
        ///INDIGO
        ///PURPLE
        ///ORANGE
        ///YELLOW
        ///1000:WHITE.
        /// </summary>
        internal static string Audacity {
            get {
                return ResourceManager.GetString("Audacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF9BDDFB.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLACK
        ///1000:WHITE.
        /// </summary>
        internal static string MonoChrome {
            get {
                return ResourceManager.GetString("MonoChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //BACKGROUND
        ///PURPLE
        ///ORANGE
        ///1000:WHITE
        /////VALUE
        ///PURPLE
        ///1000:BLUE.
        /// </summary>
        internal static string RetroVibes {
            get {
                return ResourceManager.GetString("RetroVibes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DARKRED
        ///RED
        ///YELLOW
        ///1000:GREEN.
        /// </summary>
        internal static string TrafficLight {
            get {
                return ResourceManager.GetString("TrafficLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //BACKGROUND
        ///#4C000000
        /////VALUE
        ///#FFFFFFFF.
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF9BDDFB
        ///700:#FF9BDDFB
        ///1000:#009BDDFB.
        /// </summary>
        internal static string Transparent_Blue {
            get {
                return ResourceManager.GetString("Transparent_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFFFF
        ///700:#FFFFFFFF
        ///1000:#00FFFFFF.
        /// </summary>
        internal static string Transparent_White {
            get {
                return ResourceManager.GetString("Transparent_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFFFF.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
    }
}
