//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.UI.Windows.Themes.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdamantineTheme_Description {
            get {
                return ResourceManager.GetString("AdamantineTheme.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adamantine.
        /// </summary>
        internal static string AdamantineTheme_Name {
            get {
                return ResourceManager.GetString("AdamantineTheme.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Aero2Theme_Description {
            get {
                return ResourceManager.GetString("Aero2Theme.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aero 2.
        /// </summary>
        internal static string Aero2Theme_Name {
            get {
                return ResourceManager.GetString("Aero2Theme.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AeroTheme_Description {
            get {
                return ResourceManager.GetString("AeroTheme.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aero.
        /// </summary>
        internal static string AeroTheme_Name {
            get {
                return ResourceManager.GetString("AeroTheme.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ClassicTheme_Description {
            get {
                return ResourceManager.GetString("ClassicTheme.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string ClassicTheme_Name {
            get {
                return ResourceManager.GetString("ClassicTheme.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audacity.
        /// </summary>
        internal static string ColorPalette_Audacity {
            get {
                return ResourceManager.GetString("ColorPalette.Audacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ColorPalette_Default {
            get {
                return ResourceManager.GetString("ColorPalette.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (Gradient).
        /// </summary>
        internal static string ColorPalette_Gradient {
            get {
                return ResourceManager.GetString("ColorPalette.Gradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono Chrome.
        /// </summary>
        internal static string ColorPalette_MonoChrome {
            get {
                return ResourceManager.GetString("ColorPalette.MonoChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retro Vibes.
        /// </summary>
        internal static string ColorPalette_RetroVibes {
            get {
                return ResourceManager.GetString("ColorPalette.RetroVibes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Light.
        /// </summary>
        internal static string ColorPalette_TrafficLight {
            get {
                return ResourceManager.GetString("ColorPalette.TrafficLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string ColorPalette_Transparent {
            get {
                return ResourceManager.GetString("ColorPalette.Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExpressionDarkTheme_Description {
            get {
                return ResourceManager.GetString("ExpressionDarkTheme.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Dark.
        /// </summary>
        internal static string ExpressionDarkTheme_Name {
            get {
                return ResourceManager.GetString("ExpressionDarkTheme.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string General_Advanced {
            get {
                return ResourceManager.GetString("General.Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RoyaleTheme_Description {
            get {
                return ResourceManager.GetString("RoyaleTheme.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royale.
        /// </summary>
        internal static string RoyaleTheme_Name {
            get {
                return ResourceManager.GetString("RoyaleTheme.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TransparentTheme_Description {
            get {
                return ResourceManager.GetString("TransparentTheme.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string TransparentTheme_Name {
            get {
                return ResourceManager.GetString("TransparentTheme.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string TransparentThemeConfiguration_Opacity {
            get {
                return ResourceManager.GetString("TransparentThemeConfiguration.Opacity", resourceCulture);
            }
        }
    }
}
