//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.UI.Windows.WaveBar.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string General_Advanced {
            get {
                return ResourceManager.GetString("General.Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        internal static string WaveBarBehaviourConfiguration_Cache {
            get {
                return ResourceManager.GetString("WaveBarBehaviourConfiguration.Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string WaveBarBehaviourConfiguration_Mode {
            get {
                return ResourceManager.GetString("WaveBarBehaviourConfiguration.Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono.
        /// </summary>
        internal static string WaveBarBehaviourConfiguration_Mode_Mono {
            get {
                return ResourceManager.GetString("WaveBarBehaviourConfiguration.Mode.Mono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seperate.
        /// </summary>
        internal static string WaveBarBehaviourConfiguration_Mode_Seperate {
            get {
                return ResourceManager.GetString("WaveBarBehaviourConfiguration.Mode.Seperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string WaveBarBehaviourConfiguration_Resolution {
            get {
                return ResourceManager.GetString("WaveBarBehaviourConfiguration.Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMS.
        /// </summary>
        internal static string WaveBarBehaviourConfiguration_RMS {
            get {
                return ResourceManager.GetString("WaveBarBehaviourConfiguration.RMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Form.
        /// </summary>
        internal static string WaveBarBehaviourConfiguration_Section {
            get {
                return ResourceManager.GetString("WaveBarBehaviourConfiguration.Section", resourceCulture);
            }
        }
    }
}
