//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.UI.Windows.Lyrics.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Lyrics.
        /// </summary>
        internal static string ChartLyrics {
            get {
                return ResourceManager.GetString("ChartLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Url.
        /// </summary>
        internal static string ChartLyricsProviderConfiguration_BaseUrl {
            get {
                return ResourceManager.GetString("ChartLyricsProviderConfiguration.BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Confidence.
        /// </summary>
        internal static string ChartLyricsProviderConfiguration_MinConfidence {
            get {
                return ResourceManager.GetString("ChartLyricsProviderConfiguration.MinConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Lookup.
        /// </summary>
        internal static string LyricsBehaviourConfiguration_AutoLookup {
            get {
                return ResourceManager.GetString("LyricsBehaviourConfiguration.AutoLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Lookup Provider.
        /// </summary>
        internal static string LyricsBehaviourConfiguration_AutoLookupProvider {
            get {
                return ResourceManager.GetString("LyricsBehaviourConfiguration.AutoLookupProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Scroll.
        /// </summary>
        internal static string LyricsBehaviourConfiguration_AutoScroll {
            get {
                return ResourceManager.GetString("LyricsBehaviourConfiguration.AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string LyricsBehaviourConfiguration_Editor {
            get {
                return ResourceManager.GetString("LyricsBehaviourConfiguration.Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyrics.
        /// </summary>
        internal static string LyricsBehaviourConfiguration_Section {
            get {
                return ResourceManager.GetString("LyricsBehaviourConfiguration.Section", resourceCulture);
            }
        }
    }
}
