//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.Minidisc.Bass.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erasing disc.
        /// </summary>
        internal static string EraseMinidiscTask_Name {
            get {
                return ResourceManager.GetString("EraseMinidiscTask.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disc will be erased, are you sure?.
        /// </summary>
        internal static string MinidiscBehaviour_ConfirmEraseDisc {
            get {
                return ResourceManager.GetString("MinidiscBehaviour.ConfirmEraseDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disc will be written, are you sure?.
        /// </summary>
        internal static string MinidiscBehaviour_ConfirmWriteDisc {
            get {
                return ResourceManager.GetString("MinidiscBehaviour.ConfirmWriteDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disc capacity is exceeded ({0}%), are you sure?.
        /// </summary>
        internal static string MinidiscBehaviour_ConfirmWriteDiscWithoutCapacity {
            get {
                return ResourceManager.GetString("MinidiscBehaviour.ConfirmWriteDiscWithoutCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Disc.
        /// </summary>
        internal static string MinidiscBehaviour_EraseDisc {
            get {
                return ResourceManager.GetString("MinidiscBehaviour.EraseDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minidisc.
        /// </summary>
        internal static string MinidiscBehaviour_Path {
            get {
                return ResourceManager.GetString("MinidiscBehaviour.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Disc ({0}).
        /// </summary>
        internal static string MinidiscBehaviour_SendToDisc {
            get {
                return ResourceManager.GetString("MinidiscBehaviour.SendToDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Title.
        /// </summary>
        internal static string MinidiscBehaviour_SetDiscTitle {
            get {
                return ResourceManager.GetString("MinidiscBehaviour.SetDiscTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Disc.
        /// </summary>
        internal static string MinidiscBehaviour_ViewDisc {
            get {
                return ResourceManager.GetString("MinidiscBehaviour.ViewDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string MinidiscBehaviourConfiguration_Advanced {
            get {
                return ResourceManager.GetString("MinidiscBehaviourConfiguration.Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup Temp Files.
        /// </summary>
        internal static string MinidiscBehaviourConfiguration_Cleanup {
            get {
                return ResourceManager.GetString("MinidiscBehaviourConfiguration.Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc Title Script.
        /// </summary>
        internal static string MinidiscBehaviourConfiguration_DiscTitleScript {
            get {
                return ResourceManager.GetString("MinidiscBehaviourConfiguration.DiscTitleScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string MinidiscBehaviourConfiguration_Enabled {
            get {
                return ResourceManager.GetString("MinidiscBehaviourConfiguration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minidisc.
        /// </summary>
        internal static string MinidiscBehaviourConfiguration_Section {
            get {
                return ResourceManager.GetString("MinidiscBehaviourConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Name Script.
        /// </summary>
        internal static string MinidiscBehaviourConfiguration_TrackNameScript {
            get {
                return ResourceManager.GetString("MinidiscBehaviourConfiguration.TrackNameScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string MinidiscReport_Action {
            get {
                return ResourceManager.GetString("MinidiscReport.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string MinidiscReport_Add {
            get {
                return ResourceManager.GetString("MinidiscReport.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MinidiscReport_Close {
            get {
                return ResourceManager.GetString("MinidiscReport.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string MinidiscReport_Format {
            get {
                return ResourceManager.GetString("MinidiscReport.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MinidiscReport_Name {
            get {
                return ResourceManager.GetString("MinidiscReport.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string MinidiscReport_None {
            get {
                return ResourceManager.GetString("MinidiscReport.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string MinidiscReport_Time {
            get {
                return ResourceManager.GetString("MinidiscReport.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string MinidiscReport_Write {
            get {
                return ResourceManager.GetString("MinidiscReport.Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading disc.
        /// </summary>
        internal static string OpenMinidiscTask_Name {
            get {
                return ResourceManager.GetString("OpenMinidiscTask.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing disc.
        /// </summary>
        internal static string WriteMinidiscTask_Name {
            get {
                return ResourceManager.GetString("WriteMinidiscTask.Name", resourceCulture);
            }
        }
    }
}
