// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FoxTunes.Utilities.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Source\FoxTunes\FoxTunes.Core\Utilities\Templates\LibraryHierarchyViewBuilder.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class LibraryHierarchyViewBuilder : LibraryHierarchyViewBuilderBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"
CREATE TEMPORARY TABLE ""LibraryHierarchy""
AS
	WITH ""VerticalMetaData""
	AS
	(
		SELECT ""LibraryItems"".""Id"", ""LibraryItems"".""FileName"", ""MetaDataItems"".""Name"", 
			CASE 
				WHEN ""MetaDataItems"".""NumericValue"" IS NOT NULL THEN 'Numeric' 
				WHEN ""MetaDataItems"".""TextValue"" IS NOT NULL THEN 'Text' 
				WHEN ""MetaDataItems"".""FileValue"" IS NOT NULL THEN 'File' 
			END AS ""ValueType"",
				CASE 
				WHEN ""MetaDataItems"".""NumericValue"" IS NOT NULL THEN ""MetaDataItems"".""NumericValue""
				WHEN ""MetaDataItems"".""TextValue"" IS NOT NULL THEN ""MetaDataItems"".""TextValue"" 
				WHEN ""MetaDataItems"".""FileValue"" IS NOT NULL THEN ""MetaDataItems"".""FileValue""
			END AS ""Value""
		FROM ""LibraryItems""
			JOIN ""LibraryItem_MetaDataItem"" ON ""LibraryItems"".""Id"" = ""LibraryItem_MetaDataItem"".""LibraryItem_Id""
			JOIN ""MetaDataItems"" ON ""MetaDataItems"".""Id"" = ""LibraryItem_MetaDataItem"".""MetaDataItem_Id""
		ORDER BY ""LibraryItems"".""Id""
	)
	,
	""HorizontalMetaData""
	AS
	(
	");
            
            #line 32 "C:\Source\FoxTunes\FoxTunes.Core\Utilities\Templates\LibraryHierarchyViewBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(new PivotViewBuilder(
			"VerticalMetaData", 
			new[] { "Id", "FileName" }, 
			new[] { "Name" }, 
			new[] { "ValueType", "Value" }, 
			this.MetaDataNames
		).TransformText()));
            
            #line default
            #line hidden
            this.Write(@"
	)

	SELECT ""LibraryHierarchy_LibraryHierarchyLevel"".""LibraryHierarchy_Id"" AS ""LibraryHierarchy_Id"", ""LibraryHierarchyLevels"".""Id"" AS ""LibraryHierarchyLevel_Id"", ""HorizontalMetaData"".""Id"" AS ""LibraryItem_Id"",
		EXECUTE_SCRIPT
		(
			""HorizontalMetaData"".""FileName"",
			""LibraryHierarchyLevels"".""DisplayScript""
	");
            
            #line 48 "C:\Source\FoxTunes\FoxTunes.Core\Utilities\Templates\LibraryHierarchyViewBuilder.tt"

		for(var index = 0; index < this.MetaDataNames.Length; index++)
		{
			
            
            #line default
            #line hidden
            this.Write(",\"Key_");
            
            #line 51 "C:\Source\FoxTunes\FoxTunes.Core\Utilities\Templates\LibraryHierarchyViewBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write("\", \"Value_");
            
            #line 51 "C:\Source\FoxTunes\FoxTunes.Core\Utilities\Templates\LibraryHierarchyViewBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write("_Value\"");
            
            #line 51 "C:\Source\FoxTunes\FoxTunes.Core\Utilities\Templates\LibraryHierarchyViewBuilder.tt"

		}
	
            
            #line default
            #line hidden
            this.Write("\t\t) AS DisplayValue,\r\n\t\tEXECUTE_SCRIPT\r\n\t\t(\r\n\t\t\t\"HorizontalMetaData\".\"FileName\",\r" +
                    "\n\t\t\t\"LibraryHierarchyLevels\".\"SortScript\"\r\n\t");
            
            #line 59 "C:\Source\FoxTunes\FoxTunes.Core\Utilities\Templates\LibraryHierarchyViewBuilder.tt"

		for(var index = 0; index < this.MetaDataNames.Length; index++)
		{
			
            
            #line default
            #line hidden
            this.Write(",\"Key_");
            
            #line 62 "C:\Source\FoxTunes\FoxTunes.Core\Utilities\Templates\LibraryHierarchyViewBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write("\", \"Value_");
            
            #line 62 "C:\Source\FoxTunes\FoxTunes.Core\Utilities\Templates\LibraryHierarchyViewBuilder.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index));
            
            #line default
            #line hidden
            this.Write("_Value\"");
            
            #line 62 "C:\Source\FoxTunes\FoxTunes.Core\Utilities\Templates\LibraryHierarchyViewBuilder.tt"

		}
	
            
            #line default
            #line hidden
            this.Write("\t\t) AS SortValue,\r\n\t\tCASE WHEN \r\n\t\t\tEXISTS\r\n\t\t\t(\r\n\t\t\t\tSELECT * \r\n\t\t\t\tFROM \"Librar" +
                    "yHierarchy_LibraryHierarchyLevel\" AS \"LibraryHierarchy_LibraryHierarchyLevel_Cop" +
                    "y\" \r\n\t\t\t\tWHERE \"LibraryHierarchy_LibraryHierarchyLevel_Copy\".\"LibraryHierarchy_I" +
                    "d\" = \"LibraryHierarchy_LibraryHierarchyLevel\".\"LibraryHierarchy_Id\" \r\n\t\t\t\t\tAND \"" +
                    "LibraryHierarchy_LibraryHierarchyLevel_Copy\".\"LibraryHierarchyLevel_Id\" > \"Libra" +
                    "ryHierarchyLevels\".\"Id\"\r\n\t\t\t) THEN 0 \r\n\t\t\tELSE 1 \r\n\t\tEND AS \"IsLeaf\"\r\n\tFROM \"Lib" +
                    "raryHierarchyLevels\"\r\n\t\tJOIN \"LibraryHierarchy_LibraryHierarchyLevel\" \r\n\t\t\tON \"L" +
                    "ibraryHierarchyLevels\".\"Id\" = \"LibraryHierarchy_LibraryHierarchyLevel\".\"LibraryH" +
                    "ierarchyLevel_Id\"\r\n\t\tJOIN \"HorizontalMetaData\";\r\n\r\nDELETE FROM \"LibraryHierarchy" +
                    "Items\";\r\n\r\nINSERT INTO \"LibraryHierarchyItems\" (\"LibraryHierarchy_Id\", \"LibraryH" +
                    "ierarchyLevel_Id\", \"DisplayValue\", \"SortValue\", \"IsLeaf\")\r\nSELECT \"LibraryHierar" +
                    "chy_Id\", \"LibraryHierarchyLevel_Id\", \"DisplayValue\", \"SortValue\", \"IsLeaf\"\r\nFROM" +
                    " \"LibraryHierarchy\"\r\nGROUP BY \"LibraryHierarchy_Id\", \"LibraryHierarchyLevel_Id\"," +
                    " \"DisplayValue\", \"SortValue\", \"IsLeaf\";\r\n\r\nUPDATE \"LibraryHierarchyItems\"\r\nSET \"" +
                    "Parent_Id\" = \r\n(\r\n\tSELECT \"LibraryHierarchyItems_Copy\".\"Id\"\r\n\tFROM \"LibraryHiera" +
                    "rchyItems\" AS \"LibraryHierarchyItems_Copy\"\r\n\t\tJOIN \"LibraryHierarchy\" ON \"Librar" +
                    "yHierarchy\".\"LibraryHierarchy_Id\" = \"LibraryHierarchyItems\".\"LibraryHierarchy_Id" +
                    "\"\r\n\t\tAND \"LibraryHierarchy\".\"LibraryHierarchyLevel_Id\" = \"LibraryHierarchyItems\"" +
                    ".\"LibraryHierarchyLevel_Id\"\r\n\t\tAND \"LibraryHierarchy\".\"DisplayValue\" = \"LibraryH" +
                    "ierarchyItems\".\"DisplayValue\"\r\n\t\tAND \"LibraryHierarchy\".\"SortValue\" = \"LibraryHi" +
                    "erarchyItems\".\"SortValue\"\r\n\t\tAND \"LibraryHierarchy\".\"IsLeaf\" = \"LibraryHierarchy" +
                    "Items\".\"IsLeaf\"\r\n\tJOIN \"LibraryHierarchy\" AS \"LibraryHierarchy_Copy\" ON \"Library" +
                    "Hierarchy_Copy\".\"LibraryHierarchy_Id\" = \"LibraryHierarchyItems_Copy\".\"LibraryHie" +
                    "rarchy_Id\"\r\n\t\tAND \"LibraryHierarchy_Copy\".\"LibraryHierarchyLevel_Id\" = \r\n\t\t(\r\n\t\t" +
                    "\tSELECT MAX(\"LibraryHierarchyLevels\".\"Id\") \r\n\t\t\tFROM \"LibraryHierarchyLevels\" \r\n" +
                    "\t\t\t\tJOIN \"LibraryHierarchy_LibraryHierarchyLevel\" ON \"LibraryHierarchyLevels\".\"I" +
                    "d\" = \"LibraryHierarchy_LibraryHierarchyLevel\".\"LibraryHierarchyLevel_Id\"\r\n\t\t\tWHE" +
                    "RE \"LibraryHierarchyLevels\".\"Id\" < \"LibraryHierarchy\".\"LibraryHierarchyLevel_Id\"" +
                    " AND \"LibraryHierarchy_LibraryHierarchyLevel\".\"LibraryHierarchy_Id\" = \"LibraryHi" +
                    "erarchy\".\"LibraryHierarchy_Id\" \r\n\t\t)\r\n\t\tAND \"LibraryHierarchy_Copy\".\"LibraryItem" +
                    "_Id\" = \"LibraryHierarchy\".\"LibraryItem_Id\"\r\n\t\tAND \"LibraryHierarchy_Copy\".\"Displ" +
                    "ayValue\" = \"LibraryHierarchyItems_Copy\".\"DisplayValue\"\r\n\t\tAND \"LibraryHierarchy_" +
                    "Copy\".\"SortValue\" = \"LibraryHierarchyItems_Copy\".\"SortValue\"\r\n\t\tAND \"LibraryHier" +
                    "archy_Copy\".\"IsLeaf\" = \"LibraryHierarchyItems_Copy\".\"IsLeaf\"\r\n);\r\n\r\nDELETE FROM " +
                    "\"LibraryHierarchyItem_LibraryItem\";\r\n\r\nINSERT INTO \"LibraryHierarchyItem_Library" +
                    "Item\" (\"LibraryHierarchyItem_Id\", \"LibraryItem_Id\")\r\nSELECT \"LibraryHierarchyIte" +
                    "ms\".\"Id\", \"LibraryHierarchy\".\"LibraryItem_Id\"\r\nFROM \"LibraryHierarchyItems\"\r\n\tJO" +
                    "IN \"LibraryHierarchy\" ON \"LibraryHierarchy\".\"LibraryHierarchy_Id\" \r\n\t\tAND \"Libra" +
                    "ryHierarchy\".\"LibraryHierarchyLevel_Id\" = \"LibraryHierarchyItems\".\"LibraryHierar" +
                    "chyLevel_Id\"\r\n\t\tAND \"LibraryHierarchy\".\"DisplayValue\" = \"LibraryHierarchyItems\"." +
                    "\"DisplayValue\"\r\n\t\tAND \"LibraryHierarchy\".\"SortValue\" = \"LibraryHierarchyItems\".\"" +
                    "SortValue\"\r\n\t\tAND \"LibraryHierarchy\".\"IsLeaf\" = \"LibraryHierarchyItems\".\"IsLeaf\"" +
                    ";\r\n\r\nDROP TABLE \"LibraryHierarchy\";");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class LibraryHierarchyViewBuilderBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
