//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.Core.Windows.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only While Playing.
        /// </summary>
        internal static string ExecutionStateBehaviourConfiguration_OnlyWhilePlaying {
            get {
                return ResourceManager.GetString("ExecutionStateBehaviourConfiguration.OnlyWhilePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string ExecutionStateBehaviourConfiguration_Section {
            get {
                return ResourceManager.GetString("ExecutionStateBehaviourConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string ExecutionStateBehaviourConfiguration_Sleep {
            get {
                return ResourceManager.GetString("ExecutionStateBehaviourConfiguration.Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent Display Sleep.
        /// </summary>
        internal static string ExecutionStateBehaviourConfiguration_SleepDisplay {
            get {
                return ResourceManager.GetString("ExecutionStateBehaviourConfiguration.SleepDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Sleep.
        /// </summary>
        internal static string ExecutionStateBehaviourConfiguration_SleepNone {
            get {
                return ResourceManager.GetString("ExecutionStateBehaviourConfiguration.SleepNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent System Sleep.
        /// </summary>
        internal static string ExecutionStateBehaviourConfiguration_SleepSystem {
            get {
                return ResourceManager.GetString("ExecutionStateBehaviourConfiguration.SleepSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string TaskbarButtonsBehaviour_Next {
            get {
                return ResourceManager.GetString("TaskbarButtonsBehaviour.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play or pause.
        /// </summary>
        internal static string TaskbarButtonsBehaviour_PlayPause {
            get {
                return ResourceManager.GetString("TaskbarButtonsBehaviour.PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string TaskbarButtonsBehaviour_Previous {
            get {
                return ResourceManager.GetString("TaskbarButtonsBehaviour.Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskbar Buttons.
        /// </summary>
        internal static string TaskbarButtonsBehaviourConfiguration_Enabled {
            get {
                return ResourceManager.GetString("TaskbarButtonsBehaviourConfiguration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskbar Progress.
        /// </summary>
        internal static string TaskbarProgressBehaviourConfiguration_Enabled {
            get {
                return ResourceManager.GetString("TaskbarProgressBehaviourConfiguration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskbar Thumbnail.
        /// </summary>
        internal static string TaskbarThumbnailBehaviourConfiguration_Enabled {
            get {
                return ResourceManager.GetString("TaskbarThumbnailBehaviourConfiguration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows 7.
        /// </summary>
        internal static string WindowsConfiguration_Section {
            get {
                return ResourceManager.GetString("WindowsConfiguration.Section", resourceCulture);
            }
        }
    }
}
