//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.UI.Windows.LibraryBrowser.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Browser (Grid).
        /// </summary>
        internal static string LibraryBrowser_Name {
            get {
                return ResourceManager.GetString("LibraryBrowser.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library\Browser.
        /// </summary>
        internal static string LibraryBrowserBase_Path {
            get {
                return ResourceManager.GetString("LibraryBrowserBase.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string LibraryBrowserBase_Size_Large {
            get {
                return ResourceManager.GetString("LibraryBrowserBase.Size.Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string LibraryBrowserBase_Size_Medium {
            get {
                return ResourceManager.GetString("LibraryBrowserBase.Size.Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string LibraryBrowserBase_Size_Small {
            get {
                return ResourceManager.GetString("LibraryBrowserBase.Size.Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Type.
        /// </summary>
        internal static string LibraryBrowserBaseConfiguration_Image {
            get {
                return ResourceManager.GetString("LibraryBrowserBaseConfiguration.Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound.
        /// </summary>
        internal static string LibraryBrowserBaseConfiguration_Image_Compound {
            get {
                return ResourceManager.GetString("LibraryBrowserBaseConfiguration.Image.Compound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string LibraryBrowserBaseConfiguration_Image_First {
            get {
                return ResourceManager.GetString("LibraryBrowserBaseConfiguration.Image.First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Browser.
        /// </summary>
        internal static string LibraryBrowserBaseConfiguration_Section {
            get {
                return ResourceManager.GetString("LibraryBrowserBaseConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Size.
        /// </summary>
        internal static string LibraryBrowserBaseConfiguration_Size {
            get {
                return ResourceManager.GetString("LibraryBrowserBaseConfiguration.Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Browser (List).
        /// </summary>
        internal static string LibraryList_Name {
            get {
                return ResourceManager.GetString("LibraryList.Name", resourceCulture);
            }
        }
    }
}
