//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect MainWindowBounds {
            get {
                return ((global::System.Windows.Rect)(this["MainWindowBounds"]));
            }
            set {
                this["MainWindowBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.35*")]
        public string ColumnWidth_FC87DEC38708 {
            get {
                return ((string)(this["ColumnWidth_FC87DEC38708"]));
            }
            set {
                this["ColumnWidth_FC87DEC38708"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect MiniWindowBounds {
            get {
                return ((global::System.Windows.Rect)(this["MiniWindowBounds"]));
            }
            set {
                this["MiniWindowBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect SettingsWindowBounds {
            get {
                return ((global::System.Windows.Rect)(this["SettingsWindowBounds"]));
            }
            set {
                this["SettingsWindowBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.35*")]
        public string ColumnWidth_427FFD701CC2 {
            get {
                return ((string)(this["ColumnWidth_427FFD701CC2"]));
            }
            set {
                this["ColumnWidth_427FFD701CC2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1*")]
        public string ColumnHeight_6F3FDC8521DA {
            get {
                return ((string)(this["ColumnHeight_6F3FDC8521DA"]));
            }
            set {
                this["ColumnHeight_6F3FDC8521DA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect EqualizerWindowBounds {
            get {
                return ((global::System.Windows.Rect)(this["EqualizerWindowBounds"]));
            }
            set {
                this["EqualizerWindowBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect PlaylistManagerWindowBounds {
            get {
                return ((global::System.Windows.Rect)(this["PlaylistManagerWindowBounds"]));
            }
            set {
                this["PlaylistManagerWindowBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect ReportWindowBounds {
            get {
                return ((global::System.Windows.Rect)(this["ReportWindowBounds"]));
            }
            set {
                this["ReportWindowBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,0,0")]
        public global::System.Windows.Rect TempoWindowBounds {
            get {
                return ((global::System.Windows.Rect)(this["TempoWindowBounds"]));
            }
            set {
                this["TempoWindowBounds"] = value;
            }
        }
    }
}
