//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.UI.Windows.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork.
        /// </summary>
        internal static string Artwork_Name {
            get {
                return ResourceManager.GetString("Artwork.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Tasks.
        /// </summary>
        internal static string BackgroundTasks_Name {
            get {
                return ResourceManager.GetString("BackgroundTasks.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultLayoutProvider_Description {
            get {
                return ResourceManager.GetString("DefaultLayoutProvider.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultLayoutProvider_Name {
            get {
                return ResourceManager.GetString("DefaultLayoutProvider.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string DefaultPlaylist_Name {
            get {
                return ResourceManager.GetString("DefaultPlaylist.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalizer Launcher.
        /// </summary>
        internal static string Equalizer_Name {
            get {
                return ResourceManager.GetString("Equalizer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalizer.
        /// </summary>
        internal static string EqualizerDialog_Name {
            get {
                return ResourceManager.GetString("EqualizerDialog.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalizer.
        /// </summary>
        internal static string EqualizerWindow_Title {
            get {
                return ResourceManager.GetString("EqualizerWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string General_Advanced {
            get {
                return ResourceManager.GetString("General.Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string General_Cancel {
            get {
                return ResourceManager.GetString("General.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string General_OK {
            get {
                return ResourceManager.GetString("General.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string General_Search {
            get {
                return ResourceManager.GetString("General.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string General_Settings {
            get {
                return ResourceManager.GetString("General.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing.
        /// </summary>
        internal static string Info_Name {
            get {
                return ResourceManager.GetString("Info.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string KeyBindingsBehaviourConfiguration_Next {
            get {
                return ResourceManager.GetString("KeyBindingsBehaviourConfiguration.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string KeyBindingsBehaviourConfiguration_Play {
            get {
                return ResourceManager.GetString("KeyBindingsBehaviourConfiguration.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string KeyBindingsBehaviourConfiguration_Previous {
            get {
                return ResourceManager.GetString("KeyBindingsBehaviourConfiguration.Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string KeyBindingsBehaviourConfiguration_Search {
            get {
                return ResourceManager.GetString("KeyBindingsBehaviourConfiguration.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Shortcuts.
        /// </summary>
        internal static string KeyBindingsBehaviourConfiguration_Section {
            get {
                return ResourceManager.GetString("KeyBindingsBehaviourConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string KeyBindingsBehaviourConfiguration_Settings {
            get {
                return ResourceManager.GetString("KeyBindingsBehaviourConfiguration.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string KeyBindingsBehaviourConfiguration_Stop {
            get {
                return ResourceManager.GetString("KeyBindingsBehaviourConfiguration.Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Mini Player.
        /// </summary>
        internal static string KeyBindingsBehaviourConfiguration_ToggleMiniPlayer {
            get {
                return ResourceManager.GetString("KeyBindingsBehaviourConfiguration.ToggleMiniPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Playlist.
        /// </summary>
        internal static string LibraryActionsBehaviour_AppendPlaylist {
            get {
                return ResourceManager.GetString("LibraryActionsBehaviour.AppendPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string LibraryActionsBehaviour_Library {
            get {
                return ResourceManager.GetString("LibraryActionsBehaviour.Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Playlist.
        /// </summary>
        internal static string LibraryActionsBehaviour_ReplacePlaylist {
            get {
                return ResourceManager.GetString("LibraryActionsBehaviour.ReplacePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan Files.
        /// </summary>
        internal static string LibraryActionsBehaviour_Rescan {
            get {
                return ResourceManager.GetString("LibraryActionsBehaviour.Rescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string LibraryActionsBehaviour_Settings {
            get {
                return ResourceManager.GetString("LibraryActionsBehaviour.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to collection by dropping files here..
        /// </summary>
        internal static string LibraryBase_Empty {
            get {
                return ResourceManager.GetString("LibraryBase.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LibraryBase_Loading {
            get {
                return ResourceManager.GetString("LibraryBase.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        internal static string LibraryBase_Updating {
            get {
                return ResourceManager.GetString("LibraryBase.Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string LibraryRootsDialog_Cancel {
            get {
                return ResourceManager.GetString("LibraryRootsDialog.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string LibraryRootsDialog_Delete {
            get {
                return ResourceManager.GetString("LibraryRootsDialog.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Folders.
        /// </summary>
        internal static string LibraryRootsDialog_GroupHeader {
            get {
                return ResourceManager.GetString("LibraryRootsDialog.GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string LibraryRootsDialog_New {
            get {
                return ResourceManager.GetString("LibraryRootsDialog.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string LibraryRootsDialog_Path {
            get {
                return ResourceManager.GetString("LibraryRootsDialog.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string LibraryRootsDialog_Save {
            get {
                return ResourceManager.GetString("LibraryRootsDialog.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder to library..
        /// </summary>
        internal static string LibraryRootsSettings_Browse {
            get {
                return ResourceManager.GetString("LibraryRootsSettings.Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Search.
        /// </summary>
        internal static string LibrarySearch_Name {
            get {
                return ResourceManager.GetString("LibrarySearch.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Selector.
        /// </summary>
        internal static string LibrarySelector_Name {
            get {
                return ResourceManager.GetString("LibrarySelector.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string LibrarySettingsDialog_Cancel {
            get {
                return ResourceManager.GetString("LibrarySettingsDialog.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string LibrarySettingsDialog_Clear {
            get {
                return ResourceManager.GetString("LibrarySettingsDialog.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string LibrarySettingsDialog_Delete {
            get {
                return ResourceManager.GetString("LibrarySettingsDialog.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchies.
        /// </summary>
        internal static string LibrarySettingsDialog_GroupHeader {
            get {
                return ResourceManager.GetString("LibrarySettingsDialog.GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string LibrarySettingsDialog_New {
            get {
                return ResourceManager.GetString("LibrarySettingsDialog.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan.
        /// </summary>
        internal static string LibrarySettingsDialog_Rescan {
            get {
                return ResourceManager.GetString("LibrarySettingsDialog.Rescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string LibrarySettingsDialog_Reset {
            get {
                return ResourceManager.GetString("LibrarySettingsDialog.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string LibrarySettingsDialog_Save {
            get {
                return ResourceManager.GetString("LibrarySettingsDialog.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Tree.
        /// </summary>
        internal static string LibraryTree_Name {
            get {
                return ResourceManager.GetString("LibraryTree.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation.
        /// </summary>
        internal static string MetaDataName_IsCompilation {
            get {
                return ResourceManager.GetString("MetaDataName.IsCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MinimalLayoutProvider_Description {
            get {
                return ResourceManager.GetString("MinimalLayoutProvider.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal.
        /// </summary>
        internal static string MinimalLayoutProvider_Name {
            get {
                return ResourceManager.GetString("MinimalLayoutProvider.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Player Launcher.
        /// </summary>
        internal static string MiniPlayer_Name {
            get {
                return ResourceManager.GetString("MiniPlayer.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Playlist.
        /// </summary>
        internal static string MiniPlaylist_Name {
            get {
                return ResourceManager.GetString("MiniPlaylist.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Controls.
        /// </summary>
        internal static string Playback_Name {
            get {
                return ResourceManager.GetString("Playback.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to playlist by dropping files here..
        /// </summary>
        internal static string PlaylistBase_Empty {
            get {
                return ResourceManager.GetString("PlaylistBase.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string PlaylistBase_Loading {
            get {
                return ResourceManager.GetString("PlaylistBase.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        internal static string PlaylistBase_Updating {
            get {
                return ResourceManager.GetString("PlaylistBase.Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        internal static string PlaylistGroupingBehaviourConfiguration_Enabled {
            get {
                return ResourceManager.GetString("PlaylistGroupingBehaviourConfiguration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping Script.
        /// </summary>
        internal static string PlaylistGroupingBehaviourConfiguration_Script {
            get {
                return ResourceManager.GetString("PlaylistGroupingBehaviourConfiguration.Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Tabs.
        /// </summary>
        internal static string Playlists_Name {
            get {
                return ResourceManager.GetString("Playlists.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string PlaylistSortingBehaviourConfiguration_Enabled {
            get {
                return ResourceManager.GetString("PlaylistSortingBehaviourConfiguration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ProfilesBehaviour_Delete {
            get {
                return ResourceManager.GetString("ProfilesBehaviour.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ProfilesBehaviour_New {
            get {
                return ResourceManager.GetString("ProfilesBehaviour.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name.
        /// </summary>
        internal static string ProfilesBehaviour_New_Prompt {
            get {
                return ResourceManager.GetString("ProfilesBehaviour.New.Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string ProfilesBehaviour_Path {
            get {
                return ResourceManager.GetString("ProfilesBehaviour.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string ProfilesBehaviourConfiguration_Enabled {
            get {
                return ResourceManager.GetString("ProfilesBehaviourConfiguration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string ProfilesBehaviourConfiguration_Section {
            get {
                return ResourceManager.GetString("ProfilesBehaviourConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Launcher.
        /// </summary>
        internal static string Settings_Name {
            get {
                return ResourceManager.GetString("Settings.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a sub page..
        /// </summary>
        internal static string SettingsDialog_EmptyPage {
            get {
                return ResourceManager.GetString("SettingsDialog.EmptyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        internal static string SettingsDialog_GroupHeader {
            get {
                return ResourceManager.GetString("SettingsDialog.GroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        internal static string SettingsDialog_ResetAll {
            get {
                return ResourceManager.GetString("SettingsDialog.ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Page.
        /// </summary>
        internal static string SettingsDialog_ResetPage {
            get {
                return ResourceManager.GetString("SettingsDialog.ResetPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsDialog_Save {
            get {
                return ResourceManager.GetString("SettingsDialog.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsWindow_Title {
            get {
                return ResourceManager.GetString("SettingsWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        internal static string Shuffle_Name {
            get {
                return ResourceManager.GetString("Shuffle.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seekbar.
        /// </summary>
        internal static string StreamPosition_Name {
            get {
                return ResourceManager.GetString("StreamPosition.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo Launcher.
        /// </summary>
        internal static string Tempo_Name {
            get {
                return ResourceManager.GetString("Tempo.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo.
        /// </summary>
        internal static string TempoDialog_Name {
            get {
                return ResourceManager.GetString("TempoDialog.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string UIComponentRole_Container {
            get {
                return ResourceManager.GetString("UIComponentRole.Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSP.
        /// </summary>
        internal static string UIComponentRole_DSP {
            get {
                return ResourceManager.GetString("UIComponentRole.DSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string UIComponentRole_Info {
            get {
                return ResourceManager.GetString("UIComponentRole.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        internal static string UIComponentRole_Launcher {
            get {
                return ResourceManager.GetString("UIComponentRole.Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string UIComponentRole_Library {
            get {
                return ResourceManager.GetString("UIComponentRole.Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string UIComponentRole_None {
            get {
                return ResourceManager.GetString("UIComponentRole.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        internal static string UIComponentRole_Playback {
            get {
                return ResourceManager.GetString("UIComponentRole.Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string UIComponentRole_Playlist {
            get {
                return ResourceManager.GetString("UIComponentRole.Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string UIComponentRole_System {
            get {
                return ResourceManager.GetString("UIComponentRole.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        internal static string UIComponentRole_Visualization {
            get {
                return ResourceManager.GetString("UIComponentRole.Visualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization unavailable..
        /// </summary>
        internal static string Visualization_Unavailable {
            get {
                return ResourceManager.GetString("Visualization.Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mixer is required for rendering, check your output settings..
        /// </summary>
        internal static string Visualization_UnavailableDetail {
            get {
                return ResourceManager.GetString("Visualization.UnavailableDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT Size.
        /// </summary>
        internal static string VisualizationBehaviourConfiguration_FFTSize {
            get {
                return ResourceManager.GetString("VisualizationBehaviourConfiguration.FFTSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Interval.
        /// </summary>
        internal static string VisualizationBehaviourConfiguration_Interval {
            get {
                return ResourceManager.GetString("VisualizationBehaviourConfiguration.Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string VisualizationBehaviourConfiguration_Quality {
            get {
                return ResourceManager.GetString("VisualizationBehaviourConfiguration.Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string VisualizationBehaviourConfiguration_Quality_High {
            get {
                return ResourceManager.GetString("VisualizationBehaviourConfiguration.Quality.High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string VisualizationBehaviourConfiguration_Quality_Low {
            get {
                return ResourceManager.GetString("VisualizationBehaviourConfiguration.Quality.Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizations.
        /// </summary>
        internal static string VisualizationBehaviourConfiguration_Section {
            get {
                return ResourceManager.GetString("VisualizationBehaviourConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth.
        /// </summary>
        internal static string VisualizationBehaviourConfiguration_Smooth {
            get {
                return ResourceManager.GetString("VisualizationBehaviourConfiguration.Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth Factor.
        /// </summary>
        internal static string VisualizationBehaviourConfiguration_SmoothFactor {
            get {
                return ResourceManager.GetString("VisualizationBehaviourConfiguration.SmoothFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume_Name {
            get {
                return ResourceManager.GetString("Volume.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Counters.
        /// </summary>
        internal static string WindowsUserInterfaceConfiguration_Counters {
            get {
                return ResourceManager.GetString("WindowsUserInterfaceConfiguration.Counters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Cursor Adorners.
        /// </summary>
        internal static string WindowsUserInterfaceConfiguration_Cursors {
            get {
                return ResourceManager.GetString("WindowsUserInterfaceConfiguration.Cursors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        internal static string WindowsUserInterfaceConfiguration_Glass {
            get {
                return ResourceManager.GetString("WindowsUserInterfaceConfiguration.Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string WindowsUserInterfaceConfiguration_Layout {
            get {
                return ResourceManager.GetString("WindowsUserInterfaceConfiguration.Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquee Interval.
        /// </summary>
        internal static string WindowsUserInterfaceConfiguration_MarqueeInterval {
            get {
                return ResourceManager.GetString("WindowsUserInterfaceConfiguration.MarqueeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquee Step.
        /// </summary>
        internal static string WindowsUserInterfaceConfiguration_MarqueeStep {
            get {
                return ResourceManager.GetString("WindowsUserInterfaceConfiguration.MarqueeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling Factor.
        /// </summary>
        internal static string WindowsUserInterfaceConfiguration_Scaling {
            get {
                return ResourceManager.GetString("WindowsUserInterfaceConfiguration.Scaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string WindowsUserInterfaceConfiguration_Section {
            get {
                return ResourceManager.GetString("WindowsUserInterfaceConfiguration.Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string WindowsUserInterfaceConfiguration_Theme {
            get {
                return ResourceManager.GetString("WindowsUserInterfaceConfiguration.Theme", resourceCulture);
            }
        }
    }
}
