//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TEMPORARY TABLE IF NOT EXISTS &quot;LibraryHierarchyLevelLeaf&quot;
        ///(
        ///	&quot;LibraryHierarchy_Id&quot; INTEGER NOT NULL, 
        ///	&quot;LibraryHierarchyLevel_Id&quot; INTEGER NOT NULL
        ///);
        ///CREATE UNIQUE INDEX IF NOT EXISTS &quot;IDX_LibraryHierarchyLevelLeaf&quot; ON &quot;LibraryHierarchyLevelLeaf&quot;
        ///(
        ///	&quot;LibraryHierarchy_Id&quot;
        ///);
        ///
        ///DELETE FROM &quot;LibraryHierarchyLevelLeaf&quot;;
        ///
        ///INSERT INTO &quot;LibraryHierarchyLevelLeaf&quot;
        ///SELECT LibraryHierarchy_Id, &quot;Id&quot;
        ///FROM &quot;LibraryHierarchyLevels&quot;
        ///GROUP BY &quot;LibraryHierarchy_Id&quot;
        ///HAVING MAX(&quot;Sequence&quot;)
        ///ORDER BY &quot;Seq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BeginBuildLibraryHierarchies {
            get {
                return ResourceManager.GetString("BeginBuildLibraryHierarchies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TEMPORARY TABLE IF NOT EXISTS &quot;PlaylistSort&quot;
        ///(
        ///	&quot;PlaylistItem_Id&quot; INTEGER NOT NULL, 
        ///	&quot;Value1&quot; text NULL,
        ///	&quot;Value2&quot; text NULL,
        ///	&quot;Value3&quot; text NULL,
        ///	&quot;Value4&quot; text NULL,
        ///	&quot;Value5&quot; text NULL,
        ///	&quot;Value6&quot; text NULL,
        ///	&quot;Value7&quot; text NULL,
        ///	&quot;Value8&quot; text NULL,
        ///	&quot;Value9&quot; text NULL,
        ///	&quot;Value10&quot; text NULL
        ///);
        ///
        ///CREATE TEMPORARY TABLE IF NOT EXISTS &quot;PlaylistSequence&quot;
        ///(
        ///	&quot;Id&quot; INTEGER PRIMARY KEY NOT NULL,
        ///	&quot;PlaylistItem_Id&quot; INTEGER NOT NULL
        ///);
        ///
        ///DELETE FROM &quot;PlaylistSort&quot;;
        ///DELETE FROM &quot;PlaylistS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BeginSequencePlaylistItems {
            get {
                return ResourceManager.GetString("BeginSequencePlaylistItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///CREATE TABLE [PlaylistItems](
        ///    [Id] INTEGER CONSTRAINT [sqlite_master_PK_PlaylistItems] PRIMARY KEY NOT NULL, 
        ///	[LibraryItem_Id] INTEGER NULL REFERENCES LibraryItems([Id]) ON DELETE CASCADE,
        ///    [Sequence] bigint NOT NULL, 
        ///    [DirectoryName] text NOT NULL, 
        ///    [FileName] text NOT NULL, 
        ///    [Status] bigint NOT NULL);
        ///CREATE INDEX [IDX_PlaylistItems]
        ///ON [PlaylistItems](
        ///    [Status]);
        ///CREATE TABLE [PlaylistItem_MetaDataItem](
        ///    [Id] INTEGER PRIMARY KEY NOT NULL, 
        ///    [PlaylistItem_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM &quot;LibraryHierarchyItems&quot;;
        ///
        ///INSERT INTO &quot;LibraryHierarchyItems&quot; (&quot;LibraryHierarchy_Id&quot;, &quot;LibraryHierarchyLevel_Id&quot;, &quot;DisplayValue&quot;, &quot;SortValue&quot;, &quot;IsLeaf&quot;)
        ///SELECT &quot;LibraryHierarchy_Id&quot;, &quot;LibraryHierarchyLevel_Id&quot;, &quot;DisplayValue&quot;, &quot;SortValue&quot;, &quot;IsLeaf&quot;
        ///FROM &quot;LibraryHierarchy&quot;
        ///GROUP BY &quot;LibraryHierarchy_Id&quot;, &quot;LibraryHierarchyLevel_Id&quot;, &quot;DisplayValue&quot;, &quot;SortValue&quot;, &quot;IsLeaf&quot;;
        ///
        ///UPDATE &quot;LibraryHierarchyItems&quot;
        ///SET &quot;Parent_Id&quot; = 
        ///(
        ///	SELECT &quot;LibraryHierarchyItems_Copy&quot;.&quot;Id&quot;
        ///	FROM &quot;LibraryHierarch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EndBuildLibraryHierarchies {
            get {
                return ResourceManager.GetString("EndBuildLibraryHierarchies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;PlaylistSequence&quot; (&quot;PlaylistItem_Id&quot;)
        ///SELECT &quot;PlaylistItem_Id&quot;
        ///FROM &quot;PlaylistSort&quot;
        ///ORDER BY &quot;Value1&quot;, &quot;Value2&quot;, &quot;Value3&quot;, &quot;Value4&quot;, &quot;Value5&quot;, &quot;Value6&quot;, &quot;Value7&quot;, &quot;Value8&quot;, &quot;Value9&quot;, &quot;Value10&quot;;
        ///
        ///UPDATE &quot;PlaylistItems&quot;
        ///SET &quot;Sequence&quot; = &quot;Sequence&quot; +
        ///(
        ///	SELECT &quot;Id&quot; - 1
        ///	FROM &quot;PlaylistSequence&quot;
        ///	WHERE &quot;PlaylistSequence&quot;.&quot;PlaylistItem_Id&quot; = &quot;PlaylistItems&quot;.&quot;Id&quot;
        ///)
        ///WHERE &quot;Status&quot; = @status;.
        /// </summary>
        internal static string EndSequencePlaylistItems {
            get {
                return ResourceManager.GetString("EndSequencePlaylistItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH RECURSIVE 
        ///
        ///LibraryHierarchyParents(&quot;Root&quot;, &quot;Id&quot;, &quot;Parent_Id&quot;, &quot;DisplayValue&quot;)
        ///AS
        ///(
        ///	SELECT &quot;Id&quot;, &quot;Id&quot;, &quot;Parent_Id&quot;, &quot;DisplayValue&quot;
        ///	FROM &quot;LibraryHierarchyItems&quot;
        ///	WHERE &quot;LibraryHierarchy_Id&quot; = @libraryHierarchyId
        ///		AND ((@libraryHierarchyItemId IS NULL AND &quot;LibraryHierarchyItems&quot;.&quot;Parent_Id&quot; IS NULL) OR &quot;LibraryHierarchyItems&quot;.&quot;Parent_Id&quot; = @libraryHierarchyItemId)
        ///	UNION ALL 
        ///	SELECT &quot;Root&quot;, &quot;LibraryHierarchyItems&quot;.&quot;Id&quot;, &quot;LibraryHierarchyItems&quot;.&quot;Parent_Id&quot;, &quot;LibraryHierarchyItems&quot;.&quot;DisplayVa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetLibraryHierarchyNodesWithFilter {
            get {
                return ResourceManager.GetString("GetLibraryHierarchyNodesWithFilter", resourceCulture);
            }
        }
    }
}
